### ISSUE TITLE
Vercel deployments are failing

### ISSUE THREAD

**Issue by johnboyes** [coliving-semkovo/coliving-semkovo#1]
### Describe the bug 📝:

Vercel deployments are failing, for example [this one](https://vercel.com/tobyurff/coliving-semkovo/DUTJa8jKNgdpNHZwzYK8pF9kCwgW).

### Steps to reproduce the bug 🔁:

1. Push any commit on any branch.
2. Look at the commit checks on GitHub and see that the Vercel deployment fails.

**Comment by tobyurff** [comment]
I've removed the Vercel deployment for now (there was a missing env variable). Let's discuss how to best to this – their hobby plan doesn't allow to share access, so it might make sense to create a new project in a new Vercel account that we can share credentials for via Bitwarden?!

**Comment by johnboyes** [comment]
@tobyurff I think it's important to have the deployments in Vercel working, before I submit a PR to replace ESLint & Prettier with Biome.  Don't want to have a situation where everything is good locally but Vercel is not.  (I think this is very possible, btw, because Vercel deployments run `next build` which in turn needs ESLint.  I know how to solve this, but don't want to fly blind, without Vercel deployments, while doing so). So if you're in agreement then great if you're able to do the following when you have a chance:

1. move this repo to its new location that we discussed in our last call
2. get the Vercel deployments working (I'm happy to do this, but need 1. to be done first)  🙏🏻

**Comment by tobyurff** [comment]
This is done – the issue was related to mismatched env variables on Vercel vs local env.
