### ISSUE TITLE
The `preview` script in `package.json` seems misleadingly named

### ISSUE THREAD

**Issue by johnboyes** [coliving-semkovo/coliving-semkovo#16]
### Describe the feature / bug 📝:

The `preview` task in `package.json` seems confusing to me.  It sounds to me like it should be something similar to [Vercel preview environments](https://vercel.com/docs/deployments/preview-deployments) (but locally), but it actually runs production.  That to me is dangerous. If I'm running something called preview I'd normally be very confident that I was definitely not working with production.   I'd propose to rename it something like: `production`, thoughts?

Thinking about it more, is it more that it runs a fully integrated environment, but it's not actually pointing to production (depending on our environment variables)?  If so, maybe we should rename it to something like `integration`, as that's more descriptive?

I see that `preview` is not included in [the `package.json` example in the Nextjs docs](https://nextjs.org/docs/app/building-your-application/deploying#nodejs-server).  Maybe it comes from some other form of template?  In any case, I'd propose to change it for our repo :-)

Edit: does the `preview` task relate to the [Next.js preview mode](https://nextjs.org/docs/pages/building-your-application/configuring/preview-mode), I wonder?  NB Next.js preview mode is obsolete, superseded by [draft mode](https://nextjs.org/docs/pages/building-your-application/configuring/draft-mode).

**Comment by tobyurff** [comment]
Makes sense to me! Feel free to rename it or let me know if I should.
